default_agent: uexample2
agents:
  uexample2:
    name: uexample2
    language: python
    node_version: '20'
    entrypoint: /Users/Luis_Alvarez1/Documents/Personal Documents/PersonalCode/agentcore/example2/data_agent_agentcore.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_10
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/Luis_Alvarez1/Documents/Personal Documents/PersonalCode/agentcore/example2
    aws:
      execution_role: arn:aws:iam::244639566975:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-55a2d0aabd
      execution_role_auto_create: false
      account: '244639566975'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-244639566975-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: uexample2-3A4dsc3tfi
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:244639566975:runtime/uexample2-3A4dsc3tfi
      agent_session_id: c4806da2-8f0f-4127-acf2-3e9d4674b295
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: uexample2_mem-073FLzFKZq
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:244639566975:memory/uexample2_mem-073FLzFKZq
      memory_name: uexample2_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
